package main

import "Wb00L1/internal"

func main() {
	println("Задача 1:")
	internal.Task1()
	println("Задача 2:")
	internal.Task2()
	println("Задача 3:")
	internal.Task3()
	println("Задача 4:")
	internal.Task4()
	println("Задача 5:")
	internal.Task5()
	println("Задача 6:")
	internal.Task6()
	println("Задача 7:")
	internal.Task7()
	println("Задача 8:")
	internal.Task8()
	println("Задача 9:")
	internal.Task9()
	println("Задача 10:")
	internal.Task10()
	println("Задача 11:")
	internal.Task11()
	println("Задача 12:")
	internal.Task12()
	println("Задача 13:")
	internal.Task13()
	println("Задача 14:")
	internal.Task14()
	println("Задача 15:")
	internal.Task15()
	println("Задача 16:")
	internal.Task16()
	println("Задача 17:")
	internal.Task17()
	println("Задача 18:")
	internal.Task18()
	println("Задача 19:")
	internal.Task19()
	println("Задача 20:")
	internal.Task20()
	println("Задача 21:")
	internal.Task21()
	println("Задача 22:")
	internal.Task22()
	println("Задача 23:")
	internal.Task23()
	println("Задача 24:")
	internal.Task24()
	println("Задача 25:")
	internal.Task25()
	println("Задача 26:")
	internal.Task26()

}
